name: Main

on: [push]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PCC_HOST: https://pcc-cxog5ytt4a-uw.a.run.app
      PCC_SITE_ID: wyqvIbhzhQgN4bz2VPjD
      PCC_API_KEY: ${{ secrets.PCC_API_KEY }}

    strategy:
      matrix:
        FOLDER: [nextjs-sdk, nextjs-starter, pcc, vue-sdk]

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies of root
        run: yarn install --frozen-lockfile

      - name: Remove npmconfig if exists
        run: rm -f ${{ matrix.FOLDER }}/.npmrc

      - name: Install dependencies of subfolder
        run: yarn install --frozen-lockfile
        working-directory: ${{ matrix.FOLDER }}

      # - name: Check linting
      #   run: yarn lint

      - name: Build package
        run: IS_CICD=true yarn build
        working-directory: ${{ matrix.FOLDER }}
